### ISSUE TITLE
Automate SSL certificates with Let's Encrypt

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#10]
Use Let's Encrypt to automatically request and renew SSL certificates for a farmOS Aggregator server.

Prerequisites:

- [Ansible playbook for provisioning a remote server](https://github.com/farmOS/farmOS-aggregator/issues/9)

**Comment by mstenta** [comment]
This will be a lot easier with Ansible: https://github.com/farmOS/farmOS-aggregator/issues/9

**Comment by paul121** [comment]
Being built with FastAPI, we may have Let's Encrypt capability out of the box... see [features](https://github.com/tiangolo/full-stack-fastapi-postgresql#features) near the end

**Comment by mstenta** [comment]
That's great to hear that FastAPI comes with some features for setting that up automatically.

It may be good to also leave the possibility of setting this up manually, or via other methods, so that some of that decision can be up to the host.

**Comment by paul121** [comment]
The provided `docker-compose.deploy-template.yml` uses an `nginx` proxy. This is the recommended method of deploying the aggregator.

Some documentation on configuring SSL Certs with Let's Encrypt is provided here: https://github.com/farmOS/farmOS-aggregator/blob/master/docs/deployment.md#deploying-from-docker-hub
