### ISSUE TITLE
Test farmOS auth via frontend UI

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-aggregator#12]
When managing farmOS sites from the web UI it would be great to see if a farmOS site has valid credentials.

- Include on the form for Adding and Editing farmOS site credentials to optionally 'Test farmOS authentication' before submitting changes
- Perhaps in the list of farmOS sites we could have a button to attempt authentication, return green or red to imply auth status

This could be implemented by adding another API endpoint to the backend that simply takes a `farm_id` and uses farmOS.py instance to call `farm.authenticate()` and return the response.

Another option, perhaps even simpler, would be to include farmOS.js on the frontend. Come full circle :)

**Comment by mstenta** [comment]
> Another option, perhaps even simpler, would be to include farmOS.js on the frontend.

I'd rather not do this for two main reasons:

1) It feels very much like a duplicate dependency, but more importantly:
2) I don't think we should **EVER** make the username/password available to the frontend (maybe username, but never password). Once it is in the database, it should not be readable, except by farmOS.py when making requests. (This may need to be a new feature request.)

**Comment by paul121** [comment]
Ahh ok - makes sense! 

> It feels very much like a duplicate dependency,

I agree, because this admin view is simply a tool for managing the DB via the API, it should use the API for everything it does. That should help us adhere to a well defined API

> I don't think we should EVER make the username/password available to the frontend

Right now the frontend UI does not show passwords stored in the database. There are two password fields displayed when _adding_ a farmOS site, and when _editing_ a farmOS site under the "Set Password" option. This being said, it may be possible to return the password via the API. I'll create a feature request to fix this and write a test to confirm passwords are not returned

**Comment by paul121** [comment]
Created #17 do track this

**Comment by mstenta** [comment]
Thanks! Yea we talked briefly about this on our last call, but good to make sure we have it on the list.

> Right now the frontend UI does not show passwords stored in the database.

Great!

> There are two password fields displayed when adding a farmOS site, and when editing a farmOS site under the "Set Password" option.

When *adding* a farmOS site, that's fine.

When *editing* we should leave those fields blank - so that the saved password is not passed to the frontend at all, ideally. So it would still be possible to update a password - you just wouldn't be able to *see* the password once it's been saved to the DB.

> This being said, it may be possible to return the password via the API. I'll create a feature request to fix this and write a test to confirm passwords are not returned

Great - yea I think this is important.

**Comment by paul121** [comment]
Closing this. Won't be needed with OAuth.
