### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-aggregator#14]
Need to add good documentation before the first release.

Fortunately, the application provides great documentation for the API endpoints via OpenAPI v3 at [http://localhost/docs](https://localhost/docs)

*BUT* these are only accessible if the farmOS-aggregator app is up and running :)
There is a fair amount to document on configuring and using Docker to get the app up and running. The [FastAPI Project Generator](https://github.com/tiangolo/full-stack-fastapi-postgresql) has already auto generated some of this in our README.md

**Comment by paul121** [comment]
As they have done on the Project Generator repo, adding screenshots of the OpenAPI documentation of `farm` endpoints would be a great addition.

**Comment by mstenta** [comment]
I think we can probably lean heavily on the upstream documentation - no need to duplicate what is already done (and being maintained) - with the exception maybe of setup instructions, if we have a more opinionated deployment process.

What we should focus more on is explaining WHAT the farmOS Aggregator is and WHY it is useful/necessary.

We could start by adding a page to farmOS.org (maybe at https://farmOS.org/development/aggregator). And link to that from the README file.
