### ISSUE TITLE
Add links to other bits of the farmOS ecosystem

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-aggregator#15]
Perhaps we should add links to other bits of the farmOS ecosystem in/around the web UI.

Things to include:
- farmOS.org
- farmOS API docs
- farmOS.py & farmOS.js

**Comment by paul121** [comment]
This could come with more 'branding' enhancements to farmOS-aggregator - color scheme, perhaps a logo, etc.

@mstenta 
Is there a style guide of any kind of farmOS marketing?

**Comment by mstenta** [comment]
> Is there a style guide of any kind of farmOS marketing?

No but perhaps there should be.

The official logo is available on farmOS.org: https://farmos.org/community/trademark/

farmOS itself currently uses the "Simplex" theme (aka Bootswatch) for Bootstrap 3: https://bootswatch.com/3/simplex/

farmOS Field Kit (mobile app) also uses Bootstrap, but I think @jgaehring is going to move (or has already moved) away from that.

**Comment by jgaehring** [comment]
I'm using Boostrap/Simplex still to some extent, with more and more Material elements (particularly the [Material icon set](https://material.io/tools/icons/)). I've also been using a few color variables based on the farmOS logo: https://github.com/farmOS/farmOS-client/blob/1c1e9f4cf5d41cbc70419c63f6be8b896fc8c51a/src/client/vars.css . I offset those with the cyan and orange color variables defined by SImplex.

**Comment by paul121** [comment]
Thanks @jgaehring !! I added those colors with 5cfd412358e6c3a90e2debf5538e81b34fc015ce. Looks great.

**Comment by paul121** [comment]
On the dashboard there are some links to farmOS.org and the Aggregator Docs. Emails also link to the farmOS Aggregator repo for users to get more info.

![email_screenshot](https://user-images.githubusercontent.com/3116995/74767114-15c4f980-523b-11ea-91cb-d71238472c31.png)
