### ISSUE TITLE
Web UI for viewing and managing database

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#3]
See v1.0.0 roadmap: #1

**Comment by paul121** [comment]
This commit ccdc87a87d14a0680c3b6b3e49c3889c75641489 adds views for managing farmOS profiles stored in the database.

`frontend/src/views/main/farm/Farms.vue` - list farms
`frontend/src/views/main/farm/EditFarm.vue` - edit farms
`frontend/src/views/main/farm/Farms.vue` - add farms

It's worth nothing farm profiles could be added to the DB via the OpenAPI documentation page located at [localhost/docs](http://localhost/docs) under the `Try it out` category of the `farms` endpoints.
