### ISSUE TITLE
Replicate commits to full-stack-fastapi-postgresql since Apr 13

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#37]
As I was going through the production deployment steps, I noticed there were some errors in the `README.md` that was created from the https://github.com/tiangolo/full-stack-fastapi-postgresql cookiecutter on April 13th (the initial commit to this repo: https://github.com/farmOS/farmOS-aggregator/commit/e3ab9343f269b9d41cc02489d731e17fe08d1fa1).

The `README.md` errors were fixed upstream on May 3rd in this commit: https://github.com/tiangolo/full-stack-fastapi-postgresql/commit/8bf3607d2b2e7eff776f631488ba931de2a03419

Apart from that one, it looks like there are other upstream commits that we should merge. Basically anything after April 13th that happens in the `{{cookiecutter.project_slug}}` path (I think?):

https://github.com/tiangolo/full-stack-fastapi-postgresql/commits/master/%7B%7Bcookiecutter.project_slug%7D%7D

**Comment by mstenta** [comment]
@paul121 we touched on this process briefly on our last call I think (monitoring and integrating changes from the cookiecutter). It does appear that it's relatively stable now (no new commits since May 29th). Did you say you already merged some of these?

In either case, we should have some kind of process moving forward to handle these changes and integrate them in when they happen.

**Comment by paul121** [comment]
@mstenta yeah, looks like there are some changes we should include. I did this once in a few commits on April 23rd - like this one 314047700dea1ca8c3946fb8008ddbdc94e2cacf. I pretty much made all of these "merges" manually, just looking at the upstream diffs and including the needed changes for us. I'm not sure if there's a better way? Usually there aren't *too* many things to change.

There's also times when we don't need to include *all* upstream changes. So we don't need to be strict about staying in sync, but I agree, a lot of the recent commits would be good to include!

**Comment by mstenta** [comment]
Cool yea - there's probably a way we can do it with Git, maybe some kind of subtree merge that only affects the cookiecutter subdirectory of the upstream project... not something we need to figure out ASAP, but worth having an issue open for so we can figure out a standard procedure in the future.

**Comment by paul121** [comment]
Closed via PR #54
