### ISSUE TITLE
Authenticate and store credentials for each farmOS URL

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#5]
See v1.0.0 roadmap: #1

**Comment by mstenta** [comment]
Copied from #1:

> It may also be a good opportunity to implement an OAuth2 identity provider service within farmOS that we can use to authenticate with, instead of storing raw login credentials.
> 
> Relevant issue in the farmOS queue: https://www.drupal.org/project/farm/issues/3034214

**Comment by paul121** [comment]
FastAPI should provide all the authentication we will need (features from the project generator we are using listed [here](https://github.com/tiangolo/full-stack-fastapi-postgresql#features))

- OAuth2 JWT token auth
- Included users for the farmOS-aggregator application
- farmOS-aggregator user passowords are hashed
- **farmOS passwords are stored in plaintext**

farmOS credentials can be managed via API at `/api/v1/farms/` OR Vue frontend

**Comment by mstenta** [comment]
> farmOS passwords are stored in plaintext

For future reference, here is the feature request for adding OAuth2 to farmOS itself: https://www.drupal.org/project/farm/issues/3034214
