### ISSUE TITLE
Provide API for pushing/pulling data to/from multiple farmOS instances in bulk

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#6]
See v1.0.0 roadmap: #1

We'll probably want to break this issue up into sub-issues, for each API feature we need.  My general idea is that the aggregator will provide a set of API endpoints (via Flask) that essentially allow other systems to make requests to/from all (or subsets) of the farmOS sites in bulk (thus "aggregating" the data from them, but also providing an easy API for pushing data to individual sites too).  Maybe these endpoints will essentially just be a reflection of the methods available in farmOS.py - with the added options for defining which sites the requests are sent to.

Prerequisite: [farmOS.py](https://github.com/mstenta/farmOS.py)

**Comment by paul121** [comment]
This should be mostly implemented. Endpoints are defined in `backend/app/app/api/api_v1/endpoints/farm.py`. Currently there are endpoints for managing the following:
- farmOS credentials `GET` `POST` `PUT` `DELETE`
- farmOS info `GET`
- farmOS logs `GET` `POST` `PUT` `DELETE`
- farmOS assets `GET` `POST` `PUT` `DELETE`
- farmOS terms `GET` `POST` `PUT` `DELETE`
- farmOS areas `GET` `POST` `PUT` `DELETE`

By default any query will be run on ALL farmOS profiles stored in the database (**maybe we should change this??**) *BUT* a query can be filtered to individual sites by appending farm IDs in a query parameter list: `/api/v1/farms/logs/?farm={farm id}&farm={farm2 id}&....` 

Closing
