### ISSUE TITLE
Frontend only loads 100 farms

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#85]
It seems that the frontend is only loading 100 farms from the database.

In my case, there are 112 farms in the {farm} database table, but the Aggregator is showing "100 Total Farms" on the dashboard, and "0-100 of 100" in "Manage Farms" when I select "All" in "Rows per page".

**Comment by paul121** [comment]
The `get_multi` CRUD utility for retrieving farms had a default `limit = 100`. I've removed both the `skip` and `limit` parameters from this method.

This is likely affecting more than just the displaying of farms in the UI, but any API call that requested all farms from the DB would have been capped off at 100.
