### ISSUE TITLE
Run ping-farms as a background task

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#87]
Per https://github.com/farmOS/farmOS-aggregator/issues/86, we should rework the `ping-farms` endpoint so that it runs as a background task.

**Comment by paul121** [comment]
These background tasks are pretty easy to implement. FastAPI provides some convenience around the core Starlette `BackgroundTasks` class. Docs here: https://fastapi.tiangolo.com/tutorial/background-tasks/
