### ISSUE TITLE
Dashboard shows "0 Total Farms" until you visit Manage Farms

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#88]
It seems that the data about total farm numbers is not loaded until you visit the "Manage Farms" page. So if you go to the dashboard first, it shows "0 Total Farms". If you then go to "Manage Farms" and back to the Dashboard, it shows the correct number.

**Comment by paul121** [comment]
Added `dispatchGetFarms` to `mounted()` so that the farms are loaded when viewing the dashboard. This might be the naive approach of implementing this as `farms` are reloaded each time the page is mounted - but I don't think we are too concerned about this in the admin UI at this point.
