### ISSUE TITLE
Dealing with revoked access tokens

### ISSUE THREAD

**Issue by mstenta** [farmOS/farmOS-aggregator#96]
While debugging #91, @paul121 and I discovered a potential issue we should address in the Aggregator:

If the Aggregator's access token is deleted/revoked in the farmOS server, the Aggregator has no way of knowing that, and does not give any indication of that in it's own UI. Clicking the "refresh" button in the Aggregator still appears to work, even though it isn't actually working. (I think @paul121 said this is because it's pinging `/farm.json` which always returns 200 now, after a change we made recently).

Notably, it is not currently possible to revoke access tokens via the farmOS UI. We did it manually via the database. But in the future we would like to provide the ability to revoke access via the UI. So the Aggregator needs to be able to handle that possibility.

**Comment by paul121** [comment]
Closing in favor of #114 which has updated information for 2.x
